CCXX = g++
CXXFLAGS = -std=c++11

all: class_intro constructor_intro pointer_intro static_intro overload_intro

class_intro: class_intro.cpp
	$(CCXX) $(CXXFLAGS) $^ -o $@

constructor_intro: constructor_intro.cpp
	$(CCXX) $(CXXFLAGS) $^ -o $@

pointer_intro: pointer_intro.cpp
	$(CCXX) $(CXXFLAGS) $^ -o $@

static_intro: static_intro.cpp
	$(CCXX) $(CXXFLAGS) $^ -o $@

overload_intro: overload_intro.cpp
	$(CCXX) $(CXXFLAGS) $^ -o $@
